<?php

/**
 * @file
 * Cults3D Embed module.
 */

/**
 * Implements hook_theme().
 */
function cults3d_embed_theme($existing, $type, $theme, $path) {
  return [
    'cults3d_embed_card' => [
      'variables' => [
        'model_name' => NULL,
        'description_summary' => NULL,
        'download_count' => NULL,
        'price' => NULL,
        'thumbnail_url' => NULL,
        'cults3d_url' => NULL,
      ],
      'template' => 'cults3d-embed-card',
    ],
  ];
}
